version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "sparkify_postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - sparkify_dbdata:/var/lib/postgresql/data

volumes:
  sparkify_dbdata: